2020-09-29 08:53:43,039 ERROR: Exception on /index/ [GET] [in /Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ben/py_projects/grats/app/main/routes.py", line 34, in index
    quote = get_rand_cat_quote()
  File "/Users/ben/py_projects/grats/helpers.py", line 10, in get_rand_cat_quote
    random_cat_quote = random.choice(cat_quotes_list)['text']
NameError: name 'cat_quotes_list' is not defined
2020-09-29 09:01:32,053 INFO: Microblog startup [in /Users/ben/py_projects/grats/app/__init__.py:71]
2020-09-29 09:22:03,435 INFO: Microblog startup [in /Users/ben/py_projects/grats/app/__init__.py:71]
2020-09-29 09:22:04,234 ERROR: Exception on /index/ [GET] [in /Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ben/py_projects/grats/app/main/routes.py", line 38, in index
    next_url=next_url, prev_url=prev_url)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ben/py_projects/grats/app/templates/index.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/ben/py_projects/grats/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "head"
    {%- block styles %}
  File "/Users/ben/py_projects/grats/app/templates/base.html", line 14, in block "styles"
    <link rel="stylesheet" href="{{url_for('.static', filename='styles.css')}}">
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.static' with values ['filename']. Did you mean 'static' instead?
2020-09-29 09:22:08,398 ERROR: Exception on / [GET] [in /Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ben/py_projects/grats/app/main/routes.py", line 38, in index
    next_url=next_url, prev_url=prev_url)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ben/py_projects/grats/app/templates/index.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/ben/py_projects/grats/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "head"
    {%- block styles %}
  File "/Users/ben/py_projects/grats/app/templates/base.html", line 14, in block "styles"
    <link rel="stylesheet" href="{{url_for('.static', filename='styles.css')}}">
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/ben/py_projects/grats/venv-grats/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.static' with values ['filename']. Did you mean 'static' instead?
2020-09-29 09:22:29,484 INFO: Microblog startup [in /Users/ben/py_projects/grats/app/__init__.py:71]
